// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4fzPTbOVZ01Pa5Eqn9Vu9WnfejJ8KnMY',
    appId: '1:477863304191:web:dd686782f6e6c8af5965ca',
    messagingSenderId: '477863304191',
    projectId: 'mulmet-5cb6b',
    authDomain: 'mulmet-5cb6b.firebaseapp.com',
    storageBucket: 'mulmet-5cb6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPu1xvqujEjH8YEUwv5S6P8JyAbIqtdV0',
    appId: '1:477863304191:android:e3732c20d333ab615965ca',
    messagingSenderId: '477863304191',
    projectId: 'mulmet-5cb6b',
    storageBucket: 'mulmet-5cb6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzcnD3tsUQqEQL9krVpxOCRLBZkPFf6w',
    appId: '1:477863304191:ios:6a2c66cc3b38b2ab5965ca',
    messagingSenderId: '477863304191',
    projectId: 'mulmet-5cb6b',
    storageBucket: 'mulmet-5cb6b.firebasestorage.app',
    iosBundleId: 'com.example.mulmetFlutter',
  );
}
